require 'pry'
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#                                   1,2,3,5,8,13,21,34,55,89...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

def even_fibonacci_sum(limit)
    fibonacci = [1, 2]
    sum = 2
    until fibonacci[-1] > limit 
        fibonacci << fibonacci[-1] + fibonacci[-2]
        if fibonacci[-1] % 2 == 0 && fibonacci[-1] < limit
            sum = sum + fibonacci[-1]
        end
    end
    sum
end

even_fibonacci_sum(4000000)
